# Generated by Django 4.0.3 on 2023-06-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarbageCollection', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpickup',
            name='remember_me',
            field=models.BooleanField(default=False),
        ),
    ]
