# Generated by Django 4.0.3 on 2023-06-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GarbageCollection', '0003_createpickup_remember_me'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createpickup',
            old_name='deny_request',
            new_name='comment_request',
        ),
    ]
