# Generated by Django 4.0.3 on 2023-06-01 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarbageCollection', '0004_rename_deny_request_createpickup_comment_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpickup',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
