# Generated by Django 4.0.3 on 2023-06-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GarbageCollection', '0005_createpickup_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpickup',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
