# Generated by Django 4.0.3 on 2023-05-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileInfo',
        ),
    ]
